# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(726, 889)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/logo-ncc-2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoad.sizePolicy().hasHeightForWidth())
        self.btnLoad.setSizePolicy(sizePolicy)
        self.btnLoad.setMinimumSize(QtCore.QSize(130, 23))
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout_3.addWidget(self.btnLoad)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.prjName = QtWidgets.QLineEdit(self.centralwidget)
        self.prjName.setObjectName("prjName")
        self.horizontalLayout_3.addWidget(self.prjName)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.prjManager = QtWidgets.QLineEdit(self.centralwidget)
        self.prjManager.setObjectName("prjManager")
        self.horizontalLayout_3.addWidget(self.prjManager)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setIndent(10)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.ral1 = QtWidgets.QComboBox(self.centralwidget)
        self.ral1.setMaxVisibleItems(20)
        self.ral1.setObjectName("ral1")
        self.horizontalLayout_4.addWidget(self.ral1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setIndent(10)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.ral2 = QtWidgets.QComboBox(self.centralwidget)
        self.ral2.setCurrentText("")
        self.ral2.setMaxVisibleItems(20)
        self.ral2.setObjectName("ral2")
        self.horizontalLayout_4.addWidget(self.ral2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.overhangEndR = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overhangEndR.sizePolicy().hasHeightForWidth())
        self.overhangEndR.setSizePolicy(sizePolicy)
        self.overhangEndR.setMinimumSize(QtCore.QSize(100, 0))
        self.overhangEndR.setMaximumSize(QtCore.QSize(100, 16777215))
        self.overhangEndR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overhangEndR.setMinimum(220)
        self.overhangEndR.setMaximum(434)
        self.overhangEndR.setProperty("value", 252)
        self.overhangEndR.setDisplayIntegerBase(10)
        self.overhangEndR.setObjectName("overhangEndR")
        self.gridLayout.addWidget(self.overhangEndR, 4, 6, 1, 1)
        self.overhangEndL = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overhangEndL.sizePolicy().hasHeightForWidth())
        self.overhangEndL.setSizePolicy(sizePolicy)
        self.overhangEndL.setMinimumSize(QtCore.QSize(100, 0))
        self.overhangEndL.setMaximumSize(QtCore.QSize(100, 16777215))
        self.overhangEndL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overhangEndL.setMinimum(220)
        self.overhangEndL.setMaximum(434)
        self.overhangEndL.setProperty("value", 252)
        self.overhangEndL.setDisplayIntegerBase(10)
        self.overhangEndL.setObjectName("overhangEndL")
        self.gridLayout.addWidget(self.overhangEndL, 3, 6, 1, 1)
        self.gapQty = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gapQty.sizePolicy().hasHeightForWidth())
        self.gapQty.setSizePolicy(sizePolicy)
        self.gapQty.setMinimumSize(QtCore.QSize(100, 0))
        self.gapQty.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gapQty.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gapQty.setMaximum(300)
        self.gapQty.setDisplayIntegerBase(10)
        self.gapQty.setObjectName("gapQty")
        self.gridLayout.addWidget(self.gapQty, 3, 2, 1, 1)
        self.overhangEndR_bool = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overhangEndR_bool.sizePolicy().hasHeightForWidth())
        self.overhangEndR_bool.setSizePolicy(sizePolicy)
        self.overhangEndR_bool.setMinimumSize(QtCore.QSize(20, 20))
        self.overhangEndR_bool.setStyleSheet("background-color: green;")
        self.overhangEndR_bool.setText("")
        self.overhangEndR_bool.setIndent(-1)
        self.overhangEndR_bool.setObjectName("overhangEndR_bool")
        self.gridLayout.addWidget(self.overhangEndR_bool, 4, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setLineWidth(1)
        self.label_7.setMidLineWidth(0)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.beam = QtWidgets.QComboBox(self.centralwidget)
        self.beam.setEnabled(True)
        self.beam.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.beam.setMaxVisibleItems(20)
        self.beam.setObjectName("beam")
        self.gridLayout.addWidget(self.beam, 5, 5, 1, 2)
        self.bridgeLength = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bridgeLength.sizePolicy().hasHeightForWidth())
        self.bridgeLength.setSizePolicy(sizePolicy)
        self.bridgeLength.setMinimumSize(QtCore.QSize(100, 0))
        self.bridgeLength.setMaximumSize(QtCore.QSize(100, 16777215))
        self.bridgeLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bridgeLength.setMaximum(1000000000)
        self.bridgeLength.setDisplayIntegerBase(10)
        self.bridgeLength.setObjectName("bridgeLength")
        self.gridLayout.addWidget(self.bridgeLength, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("")
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 7)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setLineWidth(1)
        self.label_12.setMidLineWidth(0)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 4, 1, 1)
        self.bridgeLength_bool = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bridgeLength_bool.sizePolicy().hasHeightForWidth())
        self.bridgeLength_bool.setSizePolicy(sizePolicy)
        self.bridgeLength_bool.setMinimumSize(QtCore.QSize(20, 20))
        self.bridgeLength_bool.setStyleSheet("background-color: green;")
        self.bridgeLength_bool.setText("")
        self.bridgeLength_bool.setObjectName("bridgeLength_bool")
        self.gridLayout.addWidget(self.bridgeLength_bool, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setLineWidth(1)
        self.label_4.setMidLineWidth(0)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.lengths_bool_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lengths_bool_3.sizePolicy().hasHeightForWidth())
        self.lengths_bool_3.setSizePolicy(sizePolicy)
        self.lengths_bool_3.setMinimumSize(QtCore.QSize(30, 20))
        self.lengths_bool_3.setMaximumSize(QtCore.QSize(20, 20))
        self.lengths_bool_3.setStyleSheet("")
        self.lengths_bool_3.setText("")
        self.lengths_bool_3.setObjectName("lengths_bool_3")
        self.gridLayout.addWidget(self.lengths_bool_3, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(13, 101, 149);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setIndent(7)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setLineWidth(1)
        self.label_11.setMidLineWidth(0)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 4, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(0, 200))
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 706, 240))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_4.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_4.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_4.setMinimumSize(QtCore.QSize(0, 200))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lengthMarker = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lengthMarker.sizePolicy().hasHeightForWidth())
        self.lengthMarker.setSizePolicy(sizePolicy)
        self.lengthMarker.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.lengthMarker.setFont(font)
        self.lengthMarker.setIndent(3)
        self.lengthMarker.setObjectName("lengthMarker")
        self.gridLayout_2.addWidget(self.lengthMarker, 2, 2, 1, 4)
        self.lengths = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.lengths.setFont(font)
        self.lengths.setWhatsThis("")
        self.lengths.setObjectName("lengths")
        self.gridLayout_2.addWidget(self.lengths, 3, 2, 1, 4)
        self.beforeGapR_bool = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beforeGapR_bool.sizePolicy().hasHeightForWidth())
        self.beforeGapR_bool.setSizePolicy(sizePolicy)
        self.beforeGapR_bool.setMinimumSize(QtCore.QSize(20, 20))
        self.beforeGapR_bool.setMaximumSize(QtCore.QSize(20, 20))
        self.beforeGapR_bool.setStyleSheet("background-color: green;")
        self.beforeGapR_bool.setText("")
        self.beforeGapR_bool.setObjectName("beforeGapR_bool")
        self.gridLayout_2.addWidget(self.beforeGapR_bool, 7, 1, 1, 1)
        self.beforeGapL = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beforeGapL.sizePolicy().hasHeightForWidth())
        self.beforeGapL.setSizePolicy(sizePolicy)
        self.beforeGapL.setMinimumSize(QtCore.QSize(100, 0))
        self.beforeGapL.setMaximumSize(QtCore.QSize(100, 16777215))
        self.beforeGapL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.beforeGapL.setMinimum(200)
        self.beforeGapL.setMaximum(1000)
        self.beforeGapL.setProperty("value", 200)
        self.beforeGapL.setDisplayIntegerBase(10)
        self.beforeGapL.setObjectName("beforeGapL")
        self.gridLayout_2.addWidget(self.beforeGapL, 5, 2, 1, 1)
        self.leftMarker = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMarker.sizePolicy().hasHeightForWidth())
        self.leftMarker.setSizePolicy(sizePolicy)
        self.leftMarker.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.leftMarker.setFont(font)
        self.leftMarker.setIndent(3)
        self.leftMarker.setObjectName("leftMarker")
        self.gridLayout_2.addWidget(self.leftMarker, 4, 5, 1, 1)
        self.beforeGapR = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beforeGapR.sizePolicy().hasHeightForWidth())
        self.beforeGapR.setSizePolicy(sizePolicy)
        self.beforeGapR.setMinimumSize(QtCore.QSize(100, 0))
        self.beforeGapR.setMaximumSize(QtCore.QSize(100, 16777215))
        self.beforeGapR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.beforeGapR.setMinimum(200)
        self.beforeGapR.setMaximum(1000)
        self.beforeGapR.setProperty("value", 200)
        self.beforeGapR.setDisplayIntegerBase(10)
        self.beforeGapR.setObjectName("beforeGapR")
        self.gridLayout_2.addWidget(self.beforeGapR, 7, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setLineWidth(1)
        self.label_8.setMidLineWidth(0)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setIndent(-1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setLineWidth(1)
        self.label_10.setMidLineWidth(0)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 7, 0, 1, 1)
        self.pillarCopy = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pillarCopy.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pillarCopy.sizePolicy().hasHeightForWidth())
        self.pillarCopy.setSizePolicy(sizePolicy)
        self.pillarCopy.setMinimumSize(QtCore.QSize(20, 20))
        self.pillarCopy.setMaximumSize(QtCore.QSize(20, 20))
        self.pillarCopy.setFlat(False)
        self.pillarCopy.setObjectName("pillarCopy")
        self.gridLayout_2.addWidget(self.pillarCopy, 9, 3, 1, 1)
        self.rightMarker = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightMarker.sizePolicy().hasHeightForWidth())
        self.rightMarker.setSizePolicy(sizePolicy)
        self.rightMarker.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.rightMarker.setFont(font)
        self.rightMarker.setIndent(3)
        self.rightMarker.setObjectName("rightMarker")
        self.gridLayout_2.addWidget(self.rightMarker, 6, 5, 1, 1)
        self.lengths_bool_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lengths_bool_2.sizePolicy().hasHeightForWidth())
        self.lengths_bool_2.setSizePolicy(sizePolicy)
        self.lengths_bool_2.setMinimumSize(QtCore.QSize(30, 20))
        self.lengths_bool_2.setMaximumSize(QtCore.QSize(20, 20))
        self.lengths_bool_2.setStyleSheet("")
        self.lengths_bool_2.setText("")
        self.lengths_bool_2.setObjectName("lengths_bool_2")
        self.gridLayout_2.addWidget(self.lengths_bool_2, 1, 1, 1, 1)
        self.lengths_bool = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lengths_bool.sizePolicy().hasHeightForWidth())
        self.lengths_bool.setSizePolicy(sizePolicy)
        self.lengths_bool.setMinimumSize(QtCore.QSize(20, 20))
        self.lengths_bool.setMaximumSize(QtCore.QSize(20, 20))
        self.lengths_bool.setStyleSheet("background-color: green;")
        self.lengths_bool.setText("")
        self.lengths_bool.setObjectName("lengths_bool")
        self.gridLayout_2.addWidget(self.lengths_bool, 3, 1, 1, 1)
        self.leftCopy = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.leftCopy.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftCopy.sizePolicy().hasHeightForWidth())
        self.leftCopy.setSizePolicy(sizePolicy)
        self.leftCopy.setMinimumSize(QtCore.QSize(20, 20))
        self.leftCopy.setMaximumSize(QtCore.QSize(20, 20))
        self.leftCopy.setObjectName("leftCopy")
        self.gridLayout_2.addWidget(self.leftCopy, 5, 3, 1, 1)
        self.rightCopy = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.rightCopy.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightCopy.sizePolicy().hasHeightForWidth())
        self.rightCopy.setSizePolicy(sizePolicy)
        self.rightCopy.setMinimumSize(QtCore.QSize(20, 20))
        self.rightCopy.setMaximumSize(QtCore.QSize(20, 20))
        self.rightCopy.setFlat(False)
        self.rightCopy.setObjectName("rightCopy")
        self.gridLayout_2.addWidget(self.rightCopy, 7, 3, 1, 1)
        self.gapsMarker = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gapsMarker.sizePolicy().hasHeightForWidth())
        self.gapsMarker.setSizePolicy(sizePolicy)
        self.gapsMarker.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.gapsMarker.setFont(font)
        self.gapsMarker.setTextFormat(QtCore.Qt.PlainText)
        self.gapsMarker.setIndent(3)
        self.gapsMarker.setObjectName("gapsMarker")
        self.gridLayout_2.addWidget(self.gapsMarker, 0, 2, 1, 4)
        self.beforeGapsR = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.beforeGapsR.setFont(font)
        self.beforeGapsR.setWhatsThis("")
        self.beforeGapsR.setObjectName("beforeGapsR")
        self.gridLayout_2.addWidget(self.beforeGapsR, 7, 5, 1, 1)
        self.pillarDist = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pillarDist.sizePolicy().hasHeightForWidth())
        self.pillarDist.setSizePolicy(sizePolicy)
        self.pillarDist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pillarDist.setMinimum(500)
        self.pillarDist.setMaximum(2000)
        self.pillarDist.setProperty("value", 1500)
        self.pillarDist.setDisplayIntegerBase(10)
        self.pillarDist.setObjectName("pillarDist")
        self.gridLayout_2.addWidget(self.pillarDist, 9, 2, 1, 1)
        self.pillarDistList = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.pillarDistList.setFont(font)
        self.pillarDistList.setWhatsThis("")
        self.pillarDistList.setObjectName("pillarDistList")
        self.gridLayout_2.addWidget(self.pillarDistList, 9, 5, 1, 1)
        self.beforeGapL_bool = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beforeGapL_bool.sizePolicy().hasHeightForWidth())
        self.beforeGapL_bool.setSizePolicy(sizePolicy)
        self.beforeGapL_bool.setMinimumSize(QtCore.QSize(20, 20))
        self.beforeGapL_bool.setMaximumSize(QtCore.QSize(20, 20))
        self.beforeGapL_bool.setStyleSheet("background-color: red;")
        self.beforeGapL_bool.setText("")
        self.beforeGapL_bool.setObjectName("beforeGapL_bool")
        self.gridLayout_2.addWidget(self.beforeGapL_bool, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setLineWidth(1)
        self.label_9.setMidLineWidth(0)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.gapWdths = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.gapWdths.setFont(font)
        self.gapWdths.setWhatsThis("")
        self.gapWdths.setObjectName("gapWdths")
        self.gridLayout_2.addWidget(self.gapWdths, 1, 2, 1, 4)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setLineWidth(1)
        self.label_13.setMidLineWidth(0)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 1, 1)
        self.beforeGapsL = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.beforeGapsL.setFont(font)
        self.beforeGapsL.setWhatsThis("")
        self.beforeGapsL.setObjectName("beforeGapsL")
        self.gridLayout_2.addWidget(self.beforeGapsL, 5, 5, 1, 1)
        self.pillarMarker = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pillarMarker.sizePolicy().hasHeightForWidth())
        self.pillarMarker.setSizePolicy(sizePolicy)
        self.pillarMarker.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.pillarMarker.setFont(font)
        self.pillarMarker.setIndent(3)
        self.pillarMarker.setObjectName("pillarMarker")
        self.gridLayout_2.addWidget(self.pillarMarker, 8, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 11, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setLineWidth(1)
        self.label_14.setMidLineWidth(0)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setIndent(-1)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 9, 0, 1, 1)
        self.pillar_bool = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pillar_bool.sizePolicy().hasHeightForWidth())
        self.pillar_bool.setSizePolicy(sizePolicy)
        self.pillar_bool.setMinimumSize(QtCore.QSize(20, 20))
        self.pillar_bool.setMaximumSize(QtCore.QSize(20, 20))
        self.pillar_bool.setStyleSheet("background-color: green;")
        self.pillar_bool.setText("")
        self.pillar_bool.setObjectName("pillar_bool")
        self.gridLayout_2.addWidget(self.pillar_bool, 9, 1, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout.addWidget(self.scrollArea_3, 8, 0, 1, 7)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setLineWidth(1)
        self.label_17.setMidLineWidth(0)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 5, 4, 1, 1)
        self.overhangEndL_bool = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overhangEndL_bool.sizePolicy().hasHeightForWidth())
        self.overhangEndL_bool.setSizePolicy(sizePolicy)
        self.overhangEndL_bool.setMinimumSize(QtCore.QSize(20, 20))
        self.overhangEndL_bool.setStyleSheet("background-color: green;")
        self.overhangEndL_bool.setText("")
        self.overhangEndL_bool.setObjectName("overhangEndL_bool")
        self.gridLayout.addWidget(self.overhangEndL_bool, 3, 5, 1, 1)
        self.gapQty_bool = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gapQty_bool.sizePolicy().hasHeightForWidth())
        self.gapQty_bool.setSizePolicy(sizePolicy)
        self.gapQty_bool.setMinimumSize(QtCore.QSize(20, 20))
        self.gapQty_bool.setStyleSheet("background-color: green;")
        self.gapQty_bool.setText("")
        self.gapQty_bool.setObjectName("gapQty_bool")
        self.gridLayout.addWidget(self.gapQty_bool, 3, 1, 1, 1)
        self.gridLayout.setRowMinimumHeight(8, 240)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setLineWidth(1)
        self.label_18.setMidLineWidth(0)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setIndent(-1)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.poConfig = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.poConfig.sizePolicy().hasHeightForWidth())
        self.poConfig.setSizePolicy(sizePolicy)
        self.poConfig.setMaximumSize(QtCore.QSize(16777215, 100))
        self.poConfig.setInputMethodHints(QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhMultiLine)
        self.poConfig.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.poConfig.setAcceptRichText(False)
        self.poConfig.setObjectName("poConfig")
        self.verticalLayout.addWidget(self.poConfig)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.useDoubleSections = QtWidgets.QCheckBox(self.centralwidget)
        self.useDoubleSections.setEnabled(True)
        self.useDoubleSections.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.useDoubleSections.setObjectName("useDoubleSections")
        self.horizontalLayout_6.addWidget(self.useDoubleSections)
        self.newFittings = QtWidgets.QCheckBox(self.centralwidget)
        self.newFittings.setEnabled(True)
        self.newFittings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.newFittings.setChecked(True)
        self.newFittings.setObjectName("newFittings")
        self.horizontalLayout_6.addWidget(self.newFittings)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 130))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 708, 94))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.serviceMessages = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serviceMessages.sizePolicy().hasHeightForWidth())
        self.serviceMessages.setSizePolicy(sizePolicy)
        self.serviceMessages.setStyleSheet("")
        self.serviceMessages.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.serviceMessages.setWordWrap(True)
        self.serviceMessages.setObjectName("serviceMessages")
        self.horizontalLayout_2.addWidget(self.serviceMessages)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 80))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 2538, 63))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resultMarker = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultMarker.sizePolicy().hasHeightForWidth())
        self.resultMarker.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.resultMarker.setFont(font)
        self.resultMarker.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.resultMarker.setObjectName("resultMarker")
        self.verticalLayout_2.addWidget(self.resultMarker)
        self.resultMessage = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultMessage.sizePolicy().hasHeightForWidth())
        self.resultMessage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(12)
        self.resultMessage.setFont(font)
        self.resultMessage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.resultMessage.setWordWrap(False)
        self.resultMessage.setIndent(-1)
        self.resultMessage.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.resultMessage.setObjectName("resultMessage")
        self.verticalLayout_2.addWidget(self.resultMessage)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.folderLabel = QtWidgets.QLabel(self.centralwidget)
        self.folderLabel.setObjectName("folderLabel")
        self.horizontalLayout.addWidget(self.folderLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        self.btnSave.setMinimumSize(QtCore.QSize(150, 25))
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerate.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGenerate.sizePolicy().hasHeightForWidth())
        self.btnGenerate.setSizePolicy(sizePolicy)
        self.btnGenerate.setMinimumSize(QtCore.QSize(100, 25))
        self.btnGenerate.setStyleSheet("")
        self.btnGenerate.setFlat(False)
        self.btnGenerate.setObjectName("btnGenerate")
        self.horizontalLayout.addWidget(self.btnGenerate)
        self.horizontalLayout.setStretch(3, 5)
        self.horizontalLayout.setStretch(5, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(6, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 726, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ral1.setCurrentIndex(-1)
        self.ral2.setCurrentIndex(-1)
        self.beam.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.prjName, self.prjManager)
        MainWindow.setTabOrder(self.prjManager, self.ral1)
        MainWindow.setTabOrder(self.ral1, self.ral2)
        MainWindow.setTabOrder(self.ral2, self.gapQty)
        MainWindow.setTabOrder(self.gapQty, self.bridgeLength)
        MainWindow.setTabOrder(self.bridgeLength, self.overhangEndL)
        MainWindow.setTabOrder(self.overhangEndL, self.overhangEndR)
        MainWindow.setTabOrder(self.overhangEndR, self.gapWdths)
        MainWindow.setTabOrder(self.gapWdths, self.lengths)
        MainWindow.setTabOrder(self.lengths, self.beforeGapL)
        MainWindow.setTabOrder(self.beforeGapL, self.leftCopy)
        MainWindow.setTabOrder(self.leftCopy, self.beforeGapsL)
        MainWindow.setTabOrder(self.beforeGapsL, self.beforeGapR)
        MainWindow.setTabOrder(self.beforeGapR, self.rightCopy)
        MainWindow.setTabOrder(self.rightCopy, self.beforeGapsR)
        MainWindow.setTabOrder(self.beforeGapsR, self.btnGenerate)
        MainWindow.setTabOrder(self.btnGenerate, self.scrollArea_3)
        MainWindow.setTabOrder(self.scrollArea_3, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.scrollArea_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "НЦК - Перила"))
        self.btnLoad.setText(_translate("MainWindow", "Загрузить"))
        self.label.setText(_translate("MainWindow", "Название проекта"))
        self.prjName.setToolTip(_translate("MainWindow", "Буквы, цифры и нижнее подчеркивание"))
        self.prjName.setStatusTip(_translate("MainWindow", "Буквы, цифры и нижнее подчеркивание"))
        self.label_2.setText(_translate("MainWindow", "Менеджер проекта"))
        self.prjManager.setToolTip(_translate("MainWindow", "Буквы, цифры и нижнее подчеркивание"))
        self.prjManager.setStatusTip(_translate("MainWindow", "Буквы, цифры и нижнее подчеркивание"))
        self.label_15.setText(_translate("MainWindow", "Цвет 1"))
        self.label_16.setText(_translate("MainWindow", "Цвет 2"))
        self.label_7.setText(_translate("MainWindow", "Количество деформационных швов"))
        self.label_5.setText(_translate("MainWindow", "Параметры моста"))
        self.label_12.setText(_translate("MainWindow", "Свес концевой правой секции"))
        self.label_4.setText(_translate("MainWindow", "Длина моста"))
        self.label_6.setText(_translate("MainWindow", "Все размеры указывать в мм"))
        self.label_11.setText(_translate("MainWindow", "Свес концевой левой секции"))
        self.lengthMarker.setText(_translate("MainWindow", "TextLabel"))
        self.lengths.setToolTip(_translate("MainWindow", "Укажите длины участков моста до и между дефшвами слева направо через пробел"))
        self.lengths.setStatusTip(_translate("MainWindow", "Укажите длины участков моста до и между дефшвами слева направо через пробел"))
        self.beforeGapL.setToolTip(_translate("MainWindow", "Для задания разных размеров перечислите их в текстовом поле через пробел для каждого шва."))
        self.beforeGapL.setStatusTip(_translate("MainWindow", "Для задания разных размеров перечислите их в текстовом поле через пробел для каждого шва."))
        self.leftMarker.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setToolTip(_translate("MainWindow", "Перечислите через пробел. Если все одинаковые укажите ширину один раз."))
        self.label_8.setStatusTip(_translate("MainWindow", "Перечислите через пробел. Если все одинаковые укажите ширину один раз."))
        self.label_8.setText(_translate("MainWindow", "Ширина швов"))
        self.label_10.setText(_translate("MainWindow", "Отступ от стоек до швов справа"))
        self.pillarCopy.setText(_translate("MainWindow", ">"))
        self.rightMarker.setText(_translate("MainWindow", "TextLabel"))
        self.leftCopy.setText(_translate("MainWindow", ">"))
        self.rightCopy.setText(_translate("MainWindow", ">"))
        self.gapsMarker.setText(_translate("MainWindow", "TextLabel"))
        self.beforeGapsR.setToolTip(_translate("MainWindow", "Для задания разных размеров перечислите их через пробел для каждого шва."))
        self.beforeGapsR.setStatusTip(_translate("MainWindow", "Для задания разных размеров перечислите их через пробел для каждого шва."))
        self.pillarDistList.setToolTip(_translate("MainWindow", "Для задания разных размеров перечислите их через пробел для каждого шва."))
        self.pillarDistList.setStatusTip(_translate("MainWindow", "Для задания разных размеров перечислите их через пробел для каждого шва."))
        self.label_9.setText(_translate("MainWindow", "Отступ от стоек до швов слева"))
        self.gapWdths.setToolTip(_translate("MainWindow", "Перечислите через пробел. Если все одинаковые укажите ширину один раз."))
        self.gapWdths.setStatusTip(_translate("MainWindow", "Перечислите через пробел. Если все одинаковые укажите ширину один раз."))
        self.label_13.setToolTip(_translate("MainWindow", "Укажите длины участков моста до и между дефшвами слева направо через пробел. Должен быть минимум 1 участок."))
        self.label_13.setStatusTip(_translate("MainWindow", "Укажите длины участков моста до и между дефшвами слева направо через пробел. Должен быть минимум 1 участок."))
        self.label_13.setText(_translate("MainWindow", "Длины участков моста"))
        self.beforeGapsL.setToolTip(_translate("MainWindow", "Для задания разных размеров перечислите их через пробел для каждого шва."))
        self.beforeGapsL.setStatusTip(_translate("MainWindow", "Для задания разных размеров перечислите их через пробел для каждого шва."))
        self.pillarMarker.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setToolTip(_translate("MainWindow", "Перечислите через пробел. Если все одинаковые укажите ширину один раз."))
        self.label_14.setStatusTip(_translate("MainWindow", "Перечислите через пробел. Если все одинаковые укажите ширину один раз."))
        self.label_14.setText(_translate("MainWindow", "Базовое расстояние между стойками"))
        self.label_17.setText(_translate("MainWindow", "Ширина \"лесенки\""))
        self.label_18.setToolTip(_translate("MainWindow", "Перечислите через пробел. Если все одинаковые укажите ширину один раз."))
        self.label_18.setStatusTip(_translate("MainWindow", "Перечислите через пробел. Если все одинаковые укажите ширину один раз."))
        self.label_18.setText(_translate("MainWindow", "Конфигурация моста (при заполнении базовое расстояние не действует)"))
        self.useDoubleSections.setText(_translate("MainWindow", "Использовать двойные секции"))
        self.newFittings.setText(_translate("MainWindow", "Использовать верхние фиттинги"))
        self.serviceMessages.setText(_translate("MainWindow", "Служебные сообщения"))
        self.resultMarker.setText(_translate("MainWindow", "TextLabel"))
        self.resultMessage.setText(_translate("MainWindow", "Результат расчета Результат расчета Результат расчета Результат расчета Результат расчета Результат расчета Результат расчета Результат расчета Результат расчета Результат расчета Результат расчета Результат расчета Результат расчета Результат расчета "))
        self.label_3.setText(_translate("MainWindow", "v0.6"))
        self.folderLabel.setText(_translate("MainWindow", "TextLabel"))
        self.btnSave.setText(_translate("MainWindow", "Сохранить проект"))
        self.btnGenerate.setText(_translate("MainWindow", "Создать сборку"))

from . import prj_rc
